module.exports = {
  list: [
    {
      name: 'Text',
      title: '文本',
      screenshot: '',
      icon: null,
      tags: null,
      package: 'rax-text',
      destructuring: 0,
      description: null,
      dependence: { package: 'rax-text', export_name: null, sub_name: null, destructuring: 0 },
      props:
        '[{"label":"行数","name":"numberOfLines","type":"Input","category":"基础属性","formItemProps":{},"props":{}},{"label":"文案","name":"text","type":"Input","category":"基础属性","formItemProps":{},"props":{}}]',
      version: '1.1.6',
      code: '',
      basicId: 45,
      versionId: 46,
      isContainer: 0,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.1.6',
      items: [],
      libraryId: 26
    },
    {
      name: 'View',
      title: '视图',
      screenshot: '',
      icon: null,
      tags: null,
      package: 'rax-view',
      destructuring: 0,
      description: null,
      dependence: { package: 'rax-view', export_name: 'View', sub_name: null, destructuring: 0 },
      props:
        '[{"label":"onLongPress","name":"onLongPress","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onAppear","name":"onAppear","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onDisappear","name":"onDisappear","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onTouchStart","name":"onTouchStart","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onTouchMove","name":"onTouchMove","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onTouchEnd","name":"onTouchEnd","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onTouchCancel","name":"onTouchCancel","type":"Function","category":"基础属性","formItemProps":{},"props":{}}]',
      version: '1.1.0',
      code: '',
      basicId: 46,
      versionId: 47,
      isContainer: 0,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: 'View',
      subName: null,
      isShow: 1,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.1.0',
      items: [],
      libraryId: 26
    },
    {
      name: 'TextInput',
      title: '富文本',
      screenshot: '',
      icon: null,
      tags: null,
      package: 'rax-textinput',
      destructuring: 0,
      description: null,
      dependence: { package: 'rax-textinput', export_name: null, sub_name: null, destructuring: 0 },
      props:
        '[{"label":"multiline","name":"multiline","type":"Switch","category":"基础属性","formItemProps":{},"props":{}},{"label":"autoComplete","name":"autoComplete","type":"Switch","category":"基础属性","formItemProps":{},"props":{}},{"label":"autoFocus","name":"autoFocus","type":"Switch","category":"基础属性","formItemProps":{},"props":{}},{"label":"editable","name":"editable","type":"Switch","category":"基础属性","formItemProps":{},"props":{}},{"label":"keyboardType","name":"keyboardType","type":"Input","category":"基础属性","formItemProps":{},"props":{}},{"label":"maxLength","name":"maxLength","type":"NumberPicker","category":"基础属性","formItemProps":{},"props":{}},{"label":"maxNumberOfLines","name":"maxNumberOfLines","type":"NumberPicker","category":"基础属性","formItemProps":{},"props":{}},{"label":"numberOfLines","name":"numberOfLines","type":"NumberPicker","category":"基础属性","formItemProps":{},"props":{}},{"label":"placeholder","name":"placeholder","type":"Input","category":"基础属性","formItemProps":{},"props":{}},{"label":"placeholderColor","name":"placeholderColor","type":"Input","category":"基础属性","formItemProps":{},"props":{}},{"label":"password","name":"password","type":"Switch","category":"基础属性","formItemProps":{},"props":{}},{"label":"secureTextEntry","name":"secureTextEntry","type":"Switch","category":"基础属性","formItemProps":{},"props":{}},{"label":"value","name":"value","type":"Input","category":"基础属性","formItemProps":{},"props":{}},{"label":"defaultValue","name":"defaultValue","type":"Input","category":"基础属性","formItemProps":{},"props":{}},{"label":"confirmType","name":"confirmType","type":"Input","category":"基础属性","formItemProps":{},"props":{}},{"label":"enableNative","name":"enableNative","type":"Switch","category":"基础属性","formItemProps":{},"props":{}},{"label":"fixed","name":"fixed","type":"Switch","category":"基础属性","formItemProps":{},"props":{}},{"label":"onChange","name":"onChange","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onChangeText","name":"onChangeText","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onFocus","name":"onFocus","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onBlur","name":"onBlur","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onInput","name":"onInput","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onConfirm","name":"onConfirm","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onAppear","name":"onAppear","type":"Function","category":"基础属性","formItemProps":{},"props":{}}]',
      version: '1.1.8',
      code: '',
      basicId: 47,
      versionId: 48,
      isContainer: 0,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.1.8',
      items: [],
      libraryId: 26
    },
    {
      name: 'Link',
      title: '链接',
      screenshot: '',
      icon: null,
      tags: null,
      package: 'rax-link',
      destructuring: 0,
      description: null,
      dependence: { package: 'rax-link', export_name: null, sub_name: null, destructuring: 0 },
      props:
        '[{"label":"href","name":"href","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"miniappHref","name":"miniappHref","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"onLoad","name":"onLoad","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onPress","name":"onPress","type":"Function","category":"基础属性","formItemProps":{},"props":{}}]',
      version: '1.1.1',
      code: '',
      basicId: 48,
      versionId: 49,
      isContainer: 0,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.1.1',
      items: [],
      libraryId: 26
    },
    {
      name: 'Icon',
      title: '图标',
      screenshot: '',
      icon: null,
      tags: null,
      package: 'rax-icon',
      destructuring: 0,
      description: null,
      dependence: { package: 'rax-icon', export_name: null, sub_name: null, destructuring: 0 },
      props:
        '[{"label":"source","name":"source","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"fontFamily","name":"fontFamily","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}}]',
      version: '1.1.2',
      code: '',
      basicId: 49,
      versionId: 50,
      isContainer: 0,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.1.2',
      items: [],
      libraryId: 26
    },
    {
      name: 'Image',
      title: '图片',
      screenshot: '',
      icon: null,
      tags: null,
      package: 'rax-image',
      destructuring: 0,
      description: null,
      dependence: { package: 'rax-image', export_name: null, sub_name: null, destructuring: 0 },
      props:
        '[{"label":"source","name":"source","type":"Mixin","category":"基础属性","formItemProps":{},"props":{"defaultType":"ObjectButton","types":["ObjectButton","Expression"],"objectButtonProps":{"formProps":{"labelCol":{"span":4},"wrapperCol":{"span":20}},"items":[{"componentName":"FormItem","props":{"name":"uri","label":"图片uri："},"children":[{"componentName":"Mixin","props":{"defaultType":"Input","types":["Input","Expression"]}}]}]}}},{"label":"fallbackSource","name":"fallbackSource","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"resizeMode","name":"resizeMode","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"mode","name":"mode","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"quality","name":"quality","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"placeholder","name":"placeholder","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"onLoad","name":"onLoad","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onError","name":"onError","type":"Function","category":"基础属性","formItemProps":{},"props":{}}]',
      version: '2.0.4',
      code: '',
      basicId: 50,
      versionId: 51,
      isContainer: 0,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '2.0.4',
      items: [],
      libraryId: 26
    },
    {
      name: 'Picture',
      title: '复杂的图片组件',
      screenshot: '',
      icon: null,
      tags: null,
      package: 'rax-picture',
      destructuring: 0,
      description: null,
      dependence: { package: 'rax-picture', export_name: null, sub_name: null, destructuring: 0 },
      props:
        '[{"label":"source","name":"source","type":"Mixin","category":"基础属性","formItemProps":{},"props":{"defaultType":"Input","types":["Input","ObjectButton","Expression"],"objectButtonProps":{"formProps":{"labelCol":{"span":4},"wrapperCol":{"span":20}},"items":[{"componentName":"FormItem","props":{"name":"uri","label":"uri："},"children":[{"componentName":"Mixin","props":{"defaultType":"Input","types":["Input","Expression"]}}]}]}}},{"label":"fallbackSource","name":"fallbackSource","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"resizeMode","name":"resizeMode","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"mode","name":"mode","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"quality","name":"quality","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"placeholder","name":"placeholder","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"lazyload","name":"lazyload","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"autoPixelRatio","name":"autoPixelRatio","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"autoRemoveScheme","name":"autoRemoveScheme","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"autoReplaceDomain","name":"autoReplaceDomain","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"autoScaling","name":"autoScaling","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"autoWebp","name":"autoWebp","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"autoCompress","name":"autoCompress","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"compressSuffix","name":"compressSuffix","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"highQuality","name":"highQuality","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"ignoreGif","name":"ignoreGif","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"forceUpdate","name":"forceUpdate","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"onLoad","name":"onLoad","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onError","name":"onError","type":"Function","category":"基础属性","formItemProps":{},"props":{}}]',
      version: '2.1.0',
      code: '',
      basicId: 51,
      versionId: 52,
      isContainer: 0,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '2.1.0',
      items: [],
      libraryId: 26
    },
    {
      name: 'Video',
      title: '视频播放',
      screenshot: '',
      icon: null,
      tags: 'video',
      package: 'rax-video',
      destructuring: 0,
      description: null,
      dependence: { package: 'rax-video', export_name: null, sub_name: null, destructuring: 0 },
      props:
        '[{"label":"播放地址","name":"src","type":"Input","category":"基础属性","formItemProps":{},"props":{}},{"label":"封面","name":"poster","type":"Input","category":"基础属性","formItemProps":{},"props":{}},{"label":"自动播放","name":"autoPlay","type":"Switch","category":"基础属性","formItemProps":{},"props":{}},{"label":"是否静音","name":"muted","type":"Switch","category":"基础属性","formItemProps":{},"props":{}},{"label":"是否循环播放","name":"loop","type":"Switch","category":"基础属性","formItemProps":{},"props":{}},{"label":"控制板","name":"controls","type":"Switch","category":"基础属性","formItemProps":{},"props":{}},{"label":"播放控制","name":"playControl","type":"Input","category":"基础属性","formItemProps":{},"props":{}}]',
      version: '1.1.3',
      code: '',
      basicId: 52,
      versionId: 53,
      isContainer: 0,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.1.3',
      items: [],
      libraryId: 26
    },
    {
      name: 'ScrollView',
      title: '滚动容器',
      screenshot: '',
      icon: null,
      tags: null,
      package: 'rax-scrollview',
      destructuring: 0,
      description: null,
      dependence: { package: 'rax-scrollview', export_name: null, sub_name: null, destructuring: 0 },
      props:
        '[{"label":"scrollEventThrottle","name":"scrollEventThrottle","type":"NumberPicker","category":"基础属性","formItemProps":{},"props":{}},{"label":"horizontal","name":"horizontal","type":"Switch","category":"基础属性","formItemProps":{},"props":{}},{"label":"showsHorizontalScrollIndicator","name":"showsHorizontalScrollIndicator","type":"Switch","category":"基础属性","formItemProps":{},"props":{}},{"label":"showsVerticalScrollIndicator","name":"showsVerticalScrollIndicator","type":"Switch","category":"基础属性","formItemProps":{},"props":{}},{"label":"onEndReachedThreshold","name":"onEndReachedThreshold","type":"NumberPicker","category":"基础属性","formItemProps":{},"props":{}},{"label":"onEndReached","name":"onEndReached","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onScroll","name":"onScroll","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onTouchStart","name":"onTouchStart","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onTouchMove","name":"onTouchMove","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onTouchEnd","name":"onTouchEnd","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onTouchCancel","name":"onTouchCancel","type":"Function","category":"基础属性","formItemProps":{},"props":{}}]',
      version: '2.0.0',
      code: '',
      basicId: 53,
      versionId: 54,
      isContainer: 1,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '2.0.0',
      items: [],
      libraryId: 26
    },
    {
      name: 'RecyclerView',
      title: '动态 View 的滚动组件',
      screenshot: '',
      icon: null,
      tags: null,
      package: 'rax-recyclerview',
      destructuring: 0,
      description: null,
      dependence: { package: 'rax-recyclerview', export_name: null, sub_name: null, destructuring: 0 },
      props:
        '[{"label":"onEndReachedThreshold","name":"onEndReachedThreshold","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"onEndReached","name":"onEndReached","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onScroll","name":"onScroll","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"itemSize","name":"itemSize","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"totalSize","name":"totalSize","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}}]',
      version: '1.1.3',
      code: '',
      basicId: 54,
      versionId: 55,
      isContainer: 1,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.1.3',
      items: [],
      libraryId: 26
    },
    {
      name: 'Waterfall',
      title: '用于实现瀑布流的列表容器',
      screenshot: '',
      icon: null,
      tags: null,
      package: 'rax-waterfall',
      destructuring: 0,
      description: null,
      dependence: { package: 'rax-waterfall', export_name: null, sub_name: null, destructuring: 0 },
      props:
        '[{"label":"dataSource","name":"dataSource","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"renderItem","name":"renderItem","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"renderHeader","name":"renderHeader","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"renderFooter","name":"renderFooter","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"columnWidth","name":"columnWidth","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"columnCount","name":"columnCount","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"columnGap","name":"columnGap","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"cellProps","name":"cellProps","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"onEndReachedThreshold","name":"onEndReachedThreshold","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"onEndReached","name":"onEndReached","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"leftGap","name":"leftGap","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"rightGap","name":"rightGap","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}}]',
      version: '1.0.0',
      code: '',
      basicId: 55,
      versionId: 56,
      isContainer: 0,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.0.0',
      items: [],
      libraryId: 26
    },
    {
      name: 'Embed',
      title: '内嵌内容容器',
      screenshot: '',
      icon: null,
      tags: null,
      package: 'rax-embed',
      destructuring: 0,
      description: null,
      dependence: { package: 'rax-embed', export_name: null, sub_name: null, destructuring: 0 },
      props:
        '[{"label":"src","name":"src","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"urlParam","name":"urlParam","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"page_inside_embed","name":"page_inside_embed","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"page_home_isweex","name":"page_home_isweex","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}}]',
      version: '1.0.0',
      code: '',
      basicId: 56,
      versionId: 57,
      isContainer: 0,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.0.0',
      items: [],
      libraryId: 26
    },
    {
      name: 'Countdown',
      title: '倒计时',
      screenshot: '',
      icon: null,
      tags: null,
      package: 'rax-countdown',
      destructuring: 0,
      description: null,
      dependence: { package: 'rax-countdown', export_name: null, sub_name: null, destructuring: 0 },
      props:
        '[{"label":"timeRemaining","name":"timeRemaining","type":"NumberPicker","category":"基础属性","formItemProps":{},"props":{}},{"label":"interval","name":"interval","type":"NumberPicker","category":"基础属性","formItemProps":{},"props":{}},{"label":"tpl","name":"tpl","type":"Input","category":"基础属性","formItemProps":{},"props":{}},{"label":"formatFunc","name":"formatFunc","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onTick","name":"onTick","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onComplete","name":"onComplete","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"timeStyle","name":"timeStyle","type":"MonacoEditor","category":"基础属性","formItemProps":{},"props":{"type":"button","language":"json"}},{"label":"secondStyle","name":"secondStyle","type":"MonacoEditor","category":"基础属性","formItemProps":{},"props":{"type":"button","language":"json"}},{"label":"textStyle","name":"textStyle","type":"MonacoEditor","category":"基础属性","formItemProps":{},"props":{"type":"button","language":"json"}},{"label":"timeWrapStyle","name":"timeWrapStyle","type":"MonacoEditor","category":"基础属性","formItemProps":{},"props":{"type":"button","language":"json"}},{"label":"timeBackground","name":"timeBackground","type":"MonacoEditor","category":"基础属性","formItemProps":{},"props":{"type":"button","language":"json"}},{"label":"timeBackgroundStyle","name":"timeBackgroundStyle","type":"MonacoEditor","category":"基础属性","formItemProps":{},"props":{"type":"button","language":"json"}}]',
      version: '*',
      code: '',
      basicId: 57,
      versionId: 58,
      isContainer: 0,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '*',
      items: [],
      libraryId: 26
    },
    {
      name: 'Canvas',
      title: 'Canvas',
      screenshot: '',
      icon: null,
      tags: null,
      package: 'rax-canvas',
      destructuring: 0,
      description: null,
      dependence: { package: 'rax-canvas', export_name: null, sub_name: null, destructuring: 0 },
      props:
        '[{"label":"className","name":"className","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"width","name":"width","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"height","name":"height","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"onClick","name":"onClick","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onLongPress","name":"onLongPress","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onTouchStart","name":"onTouchStart","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onTouchMove","name":"onTouchMove","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onTouchEnd","name":"onTouchEnd","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onTouchCancel","name":"onTouchCancel","type":"Function","category":"基础属性","formItemProps":{},"props":{}}]',
      version: '2.0.0',
      code: '',
      basicId: 58,
      versionId: 59,
      isContainer: 0,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '2.0.0',
      items: [],
      libraryId: 26
    },
    {
      name: 'RefreshControl',
      title: '滚动容器的下拉刷新功能',
      screenshot: '',
      icon: null,
      tags: null,
      package: 'rax-refreshcontrol',
      destructuring: 0,
      description: null,
      dependence: { package: 'rax-refreshcontrol', export_name: null, sub_name: null, destructuring: 0 },
      props:
        '[{"label":"refreshing","name":"refreshing","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"onRefresh","name":"onRefresh","type":"Function","category":"基础属性","formItemProps":{},"props":{}}]',
      version: '1.0.0',
      code: '',
      basicId: 59,
      versionId: 60,
      isContainer: 1,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.0.0',
      items: [],
      libraryId: 26
    },
    {
      name: 'Slider',
      title: '轮播组件',
      screenshot: '',
      icon: null,
      tags: 'slider',
      package: 'rax-slider',
      destructuring: 0,
      description: null,
      dependence: { package: 'rax-slider', export_name: null, sub_name: null, destructuring: 0 },
      props:
        '[{"label":"宽度","name":"width","type":"Input","category":"基础属性","formItemProps":{},"props":{}},{"label":"高度","name":"height","type":"Input","category":"基础属性","formItemProps":{},"props":{}},{"label":"自动播放","name":"autoPlay","type":"Switch","category":"基础属性","formItemProps":{},"props":{}},{"label":"指示点","name":"showsPagination","type":"Switch","category":"基础属性","formItemProps":{},"props":{}},{"label":"循环播放","name":"loop","type":"Switch","category":"基础属性","formItemProps":{},"props":{}},{"label":"初始页","name":"index","type":"NumberPicker","category":"基础属性","formItemProps":{},"props":{}},{"label":"间隔时间","name":"autoPlayInterval","type":"NumberPicker","category":"基础属性","formItemProps":{},"props":{}},{"label":"切换事件","name":"onChange","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"滚动方向","name":"direaction","type":"Select","category":"基础属性","formItemProps":{},"props":{"dataSource":[{"label":"horizontal","value":"horizontal"},{"label":"vertical","value":"vertical"}],"autoWidth":true}}]',
      version: '2.3.0',
      code: '',
      basicId: 60,
      versionId: 61,
      isContainer: 1,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '2.3.0',
      items: [],
      libraryId: 26
    },
    {
      name: 'Modal',
      title: '提供了弹出遮罩层的能力',
      screenshot: '',
      icon: null,
      tags: null,
      package: 'rax-modal',
      destructuring: 0,
      description: null,
      dependence: { package: 'rax-modal', export_name: null, sub_name: null, destructuring: 0 },
      props:
        '[{"label":"visible","name":"visible","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"contentStyle","name":"contentStyle","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"maskStyle","name":"maskStyle","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"onShow","name":"onShow","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"onHide","name":"onHide","type":"Function","category":"基础属性","formItemProps":{},"props":{}},{"label":"maskCanBeClick","name":"maskCanBeClick","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"delay","name":"delay","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}},{"label":"duration","name":"duration","type":"Mixin","category":"基础属性","formItemProps":{},"props":{}}]',
      version: '1.2.3',
      code: '',
      basicId: 61,
      versionId: 62,
      isContainer: 1,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: null,
      subName: null,
      isShow: 1,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '1.2.3',
      items: [],
      libraryId: 26
    },
    {
      name: 'SliderItem',
      title: 'SliderItem',
      screenshot: '',
      icon: null,
      tags: null,
      package: 'rax-slider',
      destructuring: 0,
      description: null,
      dependence: { package: 'rax-slider', export_name: 'Slider', sub_name: 'Item', destructuring: 0 },
      props: null,
      version: '2.3.0',
      code: '',
      basicId: 185,
      versionId: 186,
      isContainer: 1,
      isLayout: 0,
      parentRule: null,
      childrenRule: null,
      remarkProp: null,
      exportName: 'Slider',
      subName: 'Item',
      isShow: 1,
      devMode: 1,
      isOpen: 0,
      docLink: null,
      docDetail: null,
      dependenceVersion: '2.3.0',
      items: [],
      libraryId: 26
    }
  ],
  appList: []
};
